name: dynamite
version: 0.5.0+1
description: Provides a Dart Build System builder for generating clients from OpenAPI specifications.
homepage: https://github.com/nextcloud/neon
repository: https://github.com/nextcloud/neon/tree/main/packages/dynamite
topics:
  - openapi
  - codegen
  - build-runner
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  build: ^2.0.0
  built_collection: ^5.0.0
  built_value: ^8.9.0
  checked_yaml: ^2.0.0
  code_builder: ^4.10.0
  collection: ^1.0.0
  crypto: ^3.0.0
  dart_style: ^3.0.1
  logging: ^1.2.0
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.1.0
  pubspec_parse: ^1.2.0
  rfc_6901: ^0.2.0
  source_helper: ^1.3.0
  uri: ^1.0.0
  version: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.0
  built_value_generator: ^8.10.1
  built_value_test: ^8.10.1
  neon_lints:
    path: ../neon_lints
  test: ^1.25.15
