name: dynamite
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build: ^2.0.0
  built_collection: ^5.0.0
  built_value: ^8.0.1
  checked_yaml: ^2.0.0
  code_builder: ^4.5.0
  collection: ^1.0.0
  dart_style: ^2.0.0
  intersperse: ^2.0.0
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  uri: ^1.0.0
  version: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  built_value_generator: ^8.8.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.9
