name: dynamite
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  build: ^2.4.1
  built_collection: ^5.1.1
  built_value: ^8.6.3
  checked_yaml: ^2.0.3
  code_builder: ^4.7.0
  collection: ^1.17.2
  dart_style: ^2.3.2
  intersperse: ^2.0.0
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  built_value_generator: ^8.6.3
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.6
