name: nextcloud
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.6.3
  collection: ^1.17.1
  crypto: ^3.0.3
  crypton: ^2.2.0
  dynamite_runtime:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite_runtime
  intl: ^0.18.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  universal_io: ^2.2.2
  version: ^3.0.2
  xml: ^6.3.0
  xml_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  built_value_generator: ^8.6.3
  coverage: ^1.6.4
  dynamite:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/dynamite/dynamite
  json_serializable: ^6.7.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  path: ^1.8.3
  process_run: ^0.13.1
  test: ^1.24.7
  xml_serializable: ^2.3.0
