name: neon_lints_test
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  nextcloud: ^8.1.0

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  meta: ^1.11.0
  neon_lints:
    path: ..
