name: neon_news
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  html: ^0.15.3
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon
  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud
  provider: ^6.0.5
  rxdart: ^0.27.7
  settings:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/settings
  share_plus: ^7.0.0
  sort_box:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/sort_box
  url_launcher: ^6.1.11
  wakelock: ^0.6.2
  webview_flutter: ^4.2.0

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

dependency_overrides:
  wakelock_windows: # TODO: https://github.com/creativecreatorormaybenot/wakelock/pull/195
    git:
      url: https://github.com/fikretonuresen/wakelock
      path: wakelock_windows
      ref: 269e1dba6bca6975a0bc44da6a42e56ca7428da9

flutter:
  uses-material-design: true
  assets:
    - assets/
