name: neon_news
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  html: ^0.15.2
  material_design_icons_flutter: ^6.0.7096
  neon:
    path: ../neon
  nextcloud:
    path: ../../nextcloud
  provider: ^6.0.5
  rxdart: ^0.27.7
  settings:
    path: ../../settings
  share_plus: ^7.0.0
  sort_box:
    path: ../../sort_box
  url_launcher: ^6.1.10
  wakelock: ^0.6.2
  webview_flutter: ^4.2.0

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

dependency_overrides:
  wakelock_windows: # TODO: https://github.com/creativecreatorormaybenot/wakelock/pull/195
    git:
      url: https://github.com/creativecreatorormaybenot/wakelock
      path: wakelock_windows
      ref: 094b4a74c31e547c11525bcc050dbd06b02a1f67

flutter:
  uses-material-design: true
  assets:
    - assets/
