name: neon_lints
description: Linting package used in the nextcloud-neon project
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^7.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0

dev_dependencies:
  lint_maker: ^0.2.3
