name: news_app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.0.0
  collection: ^1.0.0
  dynamite_runtime: ^0.5.0+1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  go_router: ^15.0.0
  html: ^0.15.0
  intl: ^0.20.2
  logging: ^1.0.0
  neon_framework:
    path: ../..
  nextcloud: ^8.1.0
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  timezone: ^0.10.1
  wakelock_plus: ^1.0.0
  webview_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.5.0
  custom_lint: ^0.7.5
  go_router_builder: ^3.0.0
  neon_lints:
    path: ../../../neon_lints
  vector_graphics_compiler: ^1.1.17

flutter:
  uses-material-design: true
  assets:
    - assets/
