name: harbour
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.16.0
  crypto: ^3.0.1
  file_icons:
    path: ../file_icons
  file_picker: ^4.6.1
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_file_dialog: ^2.3.0
  flutter_html: ^3.0.0-alpha.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_native_splash: ^2.2.0+1
  flutter_rx_bloc: ^4.0.0
  flutter_svg: ^1.0.3
  html: ^0.15.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intersperse: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  material_design_icons_flutter: ^5.0.6595
  nextcloud:
    path: ../nextcloud
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  provider: ^6.0.2
  queue: ^3.1.0+1
  quick_actions: ^0.6.0+11
  rx_bloc: ^3.2.1
  rxdart: ^0.27.3
  settings:
    path: ../settings
  share_plus: ^4.0.4
  shared_preferences: ^2.0.12
  sort_box:
    path: ../sort_box
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.1
  tray_manager: ^0.1.8
  url_launcher: ^6.0.18
  wakelock: ^0.6.1+2
  webview_flutter: ^3.0.0
  window_manager: ^0.2.5
  xdg_directories: ^0.2.0+1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: f29382f
  rx_bloc_generator: ^5.1.1

dependency_overrides:
  analyzer: ^4.0.0 # https://github.com/dart-lang/language/issues/1855#issuecomment-1013212536

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/apps/
