name: neon
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  bitmap: ^0.1.3
  collection: ^1.17.1
  crypto: ^3.0.3
  file_picker: ^5.3.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_file_dialog: ^3.0.0
  flutter_local_notifications: ^14.0.0+2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.5
  go_router: ^7.1.1
  http: ^0.13.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^6.0.7096
  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud
  package_info_plus: ^4.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  provider: ^6.0.5
  quick_actions: ^1.0.3
  rxdart: ^0.27.7
  settings:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/settings
  shared_preferences: ^2.1.1
  sort_box:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/sort_box
  sqflite: ^2.2.8+2
  sqflite_common_ffi: ^2.2.5
  tray_manager: ^0.2.0
  unifiedpush: ^5.0.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.0
  window_manager: ^0.3.2
  xdg_directories: ^1.0.0
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.4
  go_router_builder: ^2.0.1
  json_serializable: ^6.6.2
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
  test: ^1.24.3

dependency_overrides:
  wakelock_windows: # TODO: https://github.com/creativecreatorormaybenot/wakelock/pull/195
    git:
      url: https://github.com/creativecreatorormaybenot/wakelock
      path: wakelock_windows
      ref: 094b4a74c31e547c11525bcc050dbd06b02a1f67

flutter:
  uses-material-design: true
  assets:
    - assets/
