name: neon
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  collection: ^1.0.0
  crypto: ^3.0.0
  file_picker: ^5.0.0
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0
  flutter_file_dialog: ^3.0.0
  flutter_local_notifications: ^16.0.0
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.0.0
  flutter_native_splash: ^2.0.0
  flutter_svg: ^2.0.0
  flutter_zxing: ^1.0.0
  go_router: ^11.0.0
  http: ^1.0.0
  image: ^4.0.0
  intersperse: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.0.0
  meta: ^1.0.0
  nextcloud:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/nextcloud
  package_info_plus: ^4.0.0
  path: ^1.0.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  provider: ^6.0.0
  quick_actions: ^1.0.0
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.0
  shared_preferences: ^2.2.1
  sort_box:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/sort_box
  sqflite: ^2.0.0
  sqflite_common_ffi: ^2.2.8-2
  tray_manager: ^0.2.0
  unifiedpush: ^5.0.0
  unifiedpush_android: ^2.0.0
  url_launcher: ^6.1.0
  vector_graphics: ^1.0.0
  window_manager: ^0.3.0
  xml: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.7
  vector_graphics_compiler: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/server/
