name: neon
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.2'

dependencies:
  collection: ^1.17.1
  crypto: ^3.0.3
  file_picker: ^5.5.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  flutter_zxing: ^1.4.1
  go_router: ^10.1.2
  http: ^1.1.0
  image: ^4.0.17
  intersperse: ^2.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.9.1
  nextcloud:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/nextcloud
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  quick_actions: ^1.0.6
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.1
  sort_box:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/sort_box
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  tray_manager: ^0.2.0
  unifiedpush: ^5.0.0
  unifiedpush_android: ^2.1.2
  url_launcher: ^6.1.14
  vector_graphics: ^1.1.7
  window_manager: ^0.3.6
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  test: ^1.24.6
  vector_graphics_compiler: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/server/
