name: neon_talk
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  built_collection: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.0
  intersperse: ^2.0.0
  intl: ^0.18.1
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^5.0.2
  rxdart: ^0.27.0
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  http: ^1.2.1
  mocktail: ^1.0.3
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  package_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins
      path: packages/package_info_plus/package_info_plus
      ref: baa336fe79c29411542fc343d332846bcd7752c1
