name: dynamite_petstore_example
description: An example showing how to use dynamite for the Petstore example API.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.0
  dynamite_runtime: ^0.5.0+1
  http: ^1.2.1
  meta: ^1.0.0
  uri: ^1.0.0

dev_dependencies:
  build_runner: ^2.5.4
  built_value_generator: ^8.10.1
  dynamite: ^0.5.0+1
  neon_lints:
    path: ../../neon_lints
