name: nextcloud_test_presets
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.0
  meta: ^1.0.0
  nextcloud: ^7.0.0
  version: ^3.0.0

dev_dependencies:
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
