name: notifications_push_repository
description: Data repository for the neon push notifications
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.27.0

dependencies:
  account_repository:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework/packages/account_repository
  built_collection: ^5.0.0
  built_value: ^8.9.2
  collection: ^1.0.0
  crypton: ^2.0.0
  http: ^1.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^8.1.0
  rxdart: ^0.28.0
  unifiedpush: ^5.0.0
  unifiedpush_android: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.13
  built_value_generator: ^8.9.2
  built_value_test: ^8.9.2
  # https://github.com/invertase/melos/issues/755
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  plugin_platform_interface: ^2.1.8
  unifiedpush_platform_interface: ^2.0.2
