name: notifications_push_repository
description: Data repository for the neon push notifications
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  account_repository:
    path: ../account_repository
  built_collection: ^5.0.0
  built_value: ^8.9.2
  collection: ^1.0.0
  crypton: ^2.0.0
  http: ^1.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    path: ../..
  nextcloud: ^8.1.0
  rxdart: ^0.28.0
  unifiedpush: ^6.0.1
  unifiedpush_android: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.1
  built_value_generator: ^8.10.1
  built_value_test: ^8.10.1
  # https://github.com/invertase/melos/issues/755
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
  plugin_platform_interface: ^2.1.8
  unifiedpush_platform_interface: ^3.0.1
