name: neon_rich_text
description: A package for rendering rich text from Nextcloud
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.0
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  intersperse: ^2.0.0
  markdown: ^7.3.0
  meta: ^1.0.0
  neon_framework:
    path: ../..
  nextcloud: ^8.1.0

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
  provider: ^6.1.5
  rxdart: ^0.28.0
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
