name: neon_rich_text
description: A package for rendering rich text from Nextcloud
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.9.0
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  intersperse: ^2.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^8.1.0

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  provider: ^6.1.2
  rxdart: ^0.28.0
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
