name: neon_files
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.13.4'

dependencies:
  collection: ^1.17.0
  file_icons:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/file_icons
  file_picker: ^5.5.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  go_router: ^10.1.2
  image_picker: ^1.0.4
  intersperse: ^2.0.0
  intl: ^0.18.1
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  open_file: ^3.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  queue: ^3.1.0+2
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  go_router_builder: ^2.3.2
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
