name: neon_files
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  collection: ^1.17.0
  file_icons:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/file_icons
  file_picker: ^5.3.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  intersperse: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon
  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud
  open_file: ^3.3.1
  path: ^1.8.3
  provider: ^6.0.5
  queue: ^3.1.0+2
  rxdart: ^0.27.7
  share_plus: ^7.0.0

dev_dependencies:
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

flutter:
  uses-material-design: true
  assets:
    - assets/
