name: app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.6
  neon:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon
  neon_files:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon_files
  neon_news:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon_news
  neon_notes:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon_notes
  neon_notifications:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/neon/neon_notifications
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

dependency_overrides:
  wakelock_windows: # TODO: https://github.com/creativecreatorormaybenot/wakelock/pull/195
    git:
      url: https://github.com/creativecreatorormaybenot/wakelock
      path: wakelock_windows
      ref: 094b4a74c31e547c11525bcc050dbd06b02a1f67

flutter:
  uses-material-design: true
  assets:
    - assets/
