name: app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  neon_files:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_files
  neon_news:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_news
  neon_notes:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_notes
  neon_notifications:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon_notifications
  vector_graphics: any

dev_dependencies:
  flutter_material_design_icons: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  shared_preferences: any
  vector_graphics_compiler: any

flutter:
  uses-material-design: true
  assets:
    - assets/
