name: account_repository
description: Data repository for the neon account management.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2
  crypto: ^3.0.3
  equatable: ^2.0.5
  http: ^1.2.2
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  neon_http_client:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework/packages/neon_http_client
  nextcloud: ^7.0.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.12
  built_value_generator: ^8.9.2
  built_value_test: ^8.9.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
