name: account_repository
description: Data repository for the neon account management.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.2
  crypto: ^3.0.3
  equatable: ^2.0.5
  http: ^1.2.2
  meta: ^1.0.0
  neon_framework:
    path: ../..
  neon_http_client:
    path: ../neon_http_client
  nextcloud: ^8.1.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.15
  built_value_generator: ^8.10.1
  built_value_test: ^8.10.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
