name: cookie_store
description: A RFC compliant cookie store
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.0.0
  timezone: ^0.10.1

dev_dependencies:
  cookie_store_conformance_tests:
    path: packages/cookie_store_conformance_tests
  neon_lints:
    path: ../neon_lints
  test: ^1.25.15
