name: notifications_app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.0.0
  dynamite_runtime: ^0.5.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  go_router: ^15.0.0
  intl: ^0.19.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    path: ../..
  neon_rich_text:
    path: ../neon_rich_text
  nextcloud: ^8.1.0
  rxdart: ^0.28.0
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.15
  built_value: ^8.9.5
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.9.0
  http: ^1.4.0
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
  provider: ^6.1.5
  url_launcher_platform_interface: ^2.3.2
  vector_graphics_compiler: ^1.1.16

flutter:
  uses-material-design: true
  assets:
    - assets/
