name: notes_app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.22.0

dependencies:
  built_collection: ^5.0.0
  crypto: ^3.0.0
  dynamite_runtime: ^0.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.0
  go_router: ^14.0.0
  http: ^1.2.1
  intl: ^0.19.0
  logging: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^7.0.0
  queue: ^3.0.0
  rxdart: ^0.28.0
  timezone: ^0.9.4
  url_launcher: ^6.1.4
  wakelock_plus: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.12
  #custom_lint: ^0.6.4
  go_router_builder: ^2.7.1
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true
  assets:
    - assets/
