name: files_app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.0.0
  collection: ^1.0.0
  dynamite_runtime: ^0.5.0+1
  file_picker: ^10.0.0
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  go_router: ^15.0.0
  image_picker: ^1.0.0
  intl: ^0.20.2
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    path: ../..
  nextcloud: ^8.1.0
  open_filex: ^4.7.0
  path: ^1.0.0
  path_provider: ^2.0.0
  queue: ^3.0.0
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  timezone: ^0.10.1
  universal_io: ^2.0.0

dev_dependencies:
  build_runner: ^2.5.1
  custom_lint: ^0.7.5
  go_router_builder: ^3.0.0
  neon_lints:
    path: ../../../neon_lints
  vector_graphics_compiler: ^1.1.17

flutter:
  uses-material-design: true
  assets:
    - assets/
