name: files_app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.27.0

dependencies:
  built_collection: ^5.0.0
  collection: ^1.0.0
  dynamite_runtime: ^0.5.0+1
  file_picker: ^9.0.0
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  go_router: ^14.0.0
  image_picker: ^1.0.0
  intl: ^0.19.0
  logging: ^1.0.0
  meta: ^1.0.0
  neon_framework:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_framework
  nextcloud: ^8.1.0
  open_filex:
    git:
      url: https://github.com/mufassalhussain/open_filex
      ref: 7ec56421afc37bb2cc3cb751b9775999cd2d9a61
  path: ^1.0.0
  path_provider: ^2.0.0
  queue: ^3.0.0
  rxdart: ^0.28.0
  share_plus: ^10.0.0
  timezone: ^0.10.0
  universal_io: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  go_router_builder: ^2.8.0
  neon_lints:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon_lints
  vector_graphics_compiler: ^1.1.16

flutter:
  uses-material-design: true
  assets:
    - assets/
