name: neon_notifications
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.0.0
  material_design_icons_flutter: ^7.0.7296
  neon:
    git:
      url: https://github.com/nextcloud/neon
      path: packages/neon/neon
  provider: ^6.0.5
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.4
  go_router_builder: ^2.2.1
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d

flutter:
  uses-material-design: true
  assets:
    - assets/
