name: Publish F-Droid nightly build

on:
  push:
    branches:
      - main

jobs:
  nightly:
    name: Publish F-Droid nightly build
    runs-on: ubuntu-22.04
    environment: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.6'
          channel: 'stable'
          cache: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Pub dependency cache
        uses: actions/cache@v3
        with:
          path: $PUB_CACHE
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Gradle dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          cd packages/neon
          flutter build apk --build-number="$(date +"%s")"
          cp build/app/outputs/apk/release/app-release.apk app-debug.apk

      - name: Upload
        uses: wardvl/f-droid-nightly-action@v2.1
        with:
          debug_keystore: ${{ secrets.DEBUG_KEYSTORE }}
          fdroid_nightly_args: -v --archive-older 10 --file app-debug.apk

      - name: F-Droid repo permission clean-up # https://github.com/actions/cache/issues/753
        run: sudo chown -R runner:docker fdroid
