name: Publish

on:
  schedule:
    - cron:  '0 5 * * *'

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  android:
    name: Android
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Install dart
        uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1
        with:
          sdk: 3.5
      - name: Setup
        run: ./tool/setup.sh

      - name: Build
        run: cd packages/neon_framework/example && fvm flutter build apk --split-per-abi --build-number="$(date +"%s")"
      - uses: ilharp/sign-android-release@2034987c31e3959f7c97e88d5e656e52e6e88bd8 # v1
        name: Sign
        with:
          buildToolsVersion: 35.0.0
          releaseDir: packages/neon_framework/example/build/app/outputs/flutter-apk
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: Android arm64-v8a
          path: packages/neon_framework/example/build/app/outputs/flutter-apk/app-arm64-v8a-release-signed.apk
          if-no-files-found: error
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: Android armeabi-v7a
          path: packages/neon_framework/example/build/app/outputs/flutter-apk/app-armeabi-v7a-release-signed.apk
          if-no-files-found: error
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: Android x86_64
          path: packages/neon_framework/example/build/app/outputs/flutter-apk/app-x86_64-release-signed.apk
          if-no-files-found: error

      - name: F-Droid nightly
        run: |
          cp packages/neon_framework/example/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk app-arm64-v8a-debug.apk
          cp packages/neon_framework/example/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk app-armeabi-v7a-debug.apk
          cp packages/neon_framework/example/build/app/outputs/flutter-apk/app-x86_64-release.apk app-x86_64-debug.apk

          sudo apt-get update && sudo apt-get install apksigner python3-pip --no-install-recommends
          python -m venv venv && source venv/bin/activate
          pip install https://gitlab.com/fdroid/fdroidserver/-/archive/9684eade0dda3663f5fb68ca02b06f7b0bb7c086/fdroidserver.tar.gz
          export DEBUG_KEYSTORE=${{ secrets.DEBUG_KEYSTORE }}
          GITHUB_REPOSITORY=provokateurin/nextcloud-neon fdroid nightly -v --archive-older 10

  linux:
    name: Linux ${{ matrix.architecture.flutter }}
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - docker: amd64
            flutter: x64
          - docker: arm64
            flutter: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3
        with:
          platforms: ${{ matrix.architecture.docker }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3
        with:
          platforms: linux/${{ matrix.architecture.docker }}

      - name: Install dart
        uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1
        with:
          sdk: 3.5
      - name: Setup
        run: ./tool/setup.sh
      - name: Build
        run: ./tool/build-app.sh linux/${{ matrix.architecture.docker }} --build-number="$(date +"%s")"

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: Linux ${{ matrix.architecture.flutter }}
          path: packages/neon_framework/example/build/linux/${{ matrix.architecture.flutter }}/release/bundle/*
          if-no-files-found: error
